<html>
<body>
<form>
  <fieldset>
    <legend>Insertar Pregunta</legend>
    <div>
    	<textarea rows="20"></textarea>
    </div>
	<div>    
		<select>
		  <option>Única</option>
		  <option>Múltiple</option>
		  <option>Texto</option>
		</select>
	</div>    
    
    <label>Label name</label>
    
    <input type="text" placeholder="Type something…">
    <span class="help-block">Example block-level help text here.</span>
    <label class="checkbox">
      <input type="checkbox"> Check me out
    </label>
    <button type="submit" class="btn">Submit</button>
  </fieldset>
</form>


</body>
</html>