<form method="post">
<fieldset>
	<legend>Insertar Pregunta</legend>
	<div id="cajapreg">
		<label class="control-label" for="description">Texto de la pregunta</label>
		<div id="texto" class="controls" >
			<textarea name="description" id="description" rows="30" style="width:100%" value="<?=(isset($viewparams['question']['description']))?$viewparams['question']['description']:'';?>"></textarea>
		</div>
	</div>

	<div id="options">
		<div id="selections">
			<label class="control-label" for="type">Tipo de Pregunta</label>
			<select name="type">
				<option value="1">Unica</option>
				<option value="2">Multiple</option>
				<option value="3">Texto</option>
			</select>
		 
			<label class="control-label" for="dificultad">Dificultad</label>
			<select name="difficulty">
				<option value="1">1</option>
				<option value="2">2</option>
				<option value="3">3</option>
			</select>
		</div>

		<div class="control-group">

			<div class="controls">
				<label class="control-label" for="answ1">Respuesta1</label>	
				<input type="text" id="answ1" name="answ1" placeholder="Respuesta1" class="answ"/>
			</div>
			<div class="controls">
				<label class="control-label" for="answ2">Respuesta2</label>	
				<input type="text" name="answ2" placeholder="Respuesta2" class="answ"/>
			</div>
			<div class="controls">
				<label class="control-label" for="answ3">Respuesta3</label>	
				<input type="text" name="answ3" placeholder="Respuesta3" class="answ"/>
			</div>
			<div class="controls">
				<label class="control-label" for="answ4">Respuesta4</label>	
				<input type="text" name="answ4" placeholder="Respuesta4" class="answ"/>
			</div>
			<div class="controls">
				<label class="control-label" for="answ5">Respuesta5</label>	
				<input type="text" name="answ5" placeholder="Respuesta5" class="answ"/>
			</div>
			<br/><br/><br/><br/><br/><br/><br/>
			<label class="control-label" for="rightansw">Respuesta Correcta</label>
			<div >
				<input type="text" name="rightansw" placeholder="Valores separados por comas" class="answ">
			</div>

			<div class="form-actions">
				<input type="submit" class="btn btn-primary btn-block" value="Guardar"></input>
				<a href="/questions/index/exam/<?=$viewparams['examID'];?>" class="btn btn-danger btn-block">Cancelar</a>
			</div>

		</div>
	</div>


</fieldset>
</form>


