<form method="post">
<fieldset>
	<legend>Actualizar Pregunta</legend>
	<div id="cajapreg">
		<label class="control-label" for="description">Texto de la pregunta</label>
		<div id="texto" class="controls" >
			<textarea name="description" id="description" rows="30" style="width:100%"> <?=(isset($viewparams['question']['description']))?$viewparams['question']['description']:'';?></textarea>
		</div>
	</div>

	<div id="options">
		<div id="selections">
			<label class="control-label" for="type">Tipo de Pregunta</label>
			<select name="type">
				<option value="1" <?=($viewparams['question']['question_type']==1)?'selected':'';?>>Unica</option>
				<option value="2" <?=($viewparams['question']['question_type']==2)?'selected':'';?>>Multiple</option>
				<option value="3" <?=($viewparams['question']['question_type']==3)?'selected':'';?>>Texto</option>
			</select>
		 
			<label class="control-label" for="dificultad">Dificultad</label>
			<select name="difficulty">
				<option value="1" <?=($viewparams['question']['question_difficulty']==1)?'selected':'';?>>1</option>
				<option value="2" <?=($viewparams['question']['question_difficulty']==2)?'selected':'';?>>2</option>
				<option value="3" <?=($viewparams['question']['question_difficulty']==3)?'selected':'';?>>3</option>
			</select>
		</div>

		<div class="control-group">

			<?php foreach($viewparams['answers'] as $key =>$value):?>
				<div class="controls">
					<label class="control-label" for="answ_<?= $value['idanswers'];?>">Respuesta<?=$key + 1;?></label>	
					<input type="text" id="answ_<?= $value['idanswers'];?>" name="answ_<?=$value['idanswers'];?>" placeholder="Respuesta<?= $key+1;?>" class="answ" value="<?=(isset($value['text']))?$value['text']:'';?>"/>
				</div>
			<?php endforeach;?>	  
		
		
			
			<br/><br/><br/><br/><br/><br/><br/>
			<label class="control-label" for="rightansw">Respuesta Correcta</label>
			<div >
				<input type="text" name="rightansw" placeholder="Valores separados por comas" class="answ" value="<?=(isset($viewparams['right']))?$viewparams['right']:'';?>">
			</div>

			<div class="form-actions">
				<input type="submit" class="btn btn-primary btn-block" value="Guardar"></input>
				<a href="/questions/index/exam/<?=$viewparams['examID'];?>" class="btn btn-danger btn-block">Cancelar</a>
			</div>

		</div>
	</div>


</fieldset>
</form>


