<h1>Users Delete</h1>
<form method="post">
<ul  class="list-unstyled">
	<input type="hidden" name="id" value="<?=(isset($viewparams['users']['idusers']))?$viewparams['users']['idusers']:'';?>"/>
	<li>
		Nombre: <?=(isset($viewparams['users']['name']))?$viewparams['users']['name']:'';?>
	</li>
	<li>
		Seguro que desea borrar el usuario
	</li>	
	<li>
		<button type="submit" name="borrar" value="Si" class="btn btn-primary">Si</button>
		<button type="submit" name="borrar" value="No" class="btn btn-primary">No</button>
	</li>
	
</ul>
</form>
