<h1>Users</h1>
<a href="/users" class="btn btn-primary btn-sm" role="button">Volver</a>
<br /><br />
<form method="post" class="form-horizontal" role="form">
	<div class="form-group">
	    <label for="inputname" class="col-sm-2 control-label">Nombre</label>
	    <div class="col-xs-3">
	      <input type="text" name="name" value="<?=(isset($viewparams['users']['name']))?$viewparams['users']['name']:'';?>" class="form-control" id="inputname" placeholder="Nombre" >
	    </div>
	</div>
	<div class="form-group">
	    <label for="inputemail" class="col-sm-2 control-label">Email</label>
	    <div class="col-xs-3">
	      <input type="text" name="email" value="<?=(isset($viewparams['users']['email']))?$viewparams['users']['email']:'';?>" class="form-control" id="inputemail" placeholder="Email" >
	    </div>
	</div>
	<div class="form-group">
	    <label for="inputpassword" class="col-sm-2 control-label">Password</label>
	    <div class="col-xs-3">
	      <input type="password" name="password" class="form-control" id="inputname" placeholder="Password" >
	    </div>
	</div>
	<div class="form-group">
	    <div class="col-sm-offset-2 col-xs-3">
	      <button type="submit" class="btn btn-default">Enviar</button>
	    </div>
	</div>
	<input type="hidden" name="id" value="<?=(isset($viewparams['users']['idusers']))?$viewparams['users']['idusers']:'';?>"/>
</form>