<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">AnguilaPerro</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/index/about">About</a></li>
            <li><a href="/index/contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
          	<?php if (isset($_SESSION['user'])){ ?>
           		<li><a>Hola <?=$_SESSION['user']['name']?></a></li>
           		<li><a href="/author/logout">Logout</a></li>
            <?php }?>
           </ul>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->
